org.gradle.jvmargs=-Xmx4G
jvm=25
minecraft_version=26.2
neoForm_version=26.2-2
# NeoForge Properties
neoforge_version=26.2.0.63
# Fabric Properties
fabric_loader_version=0.19.3

# Mod Properties
mod_version=1.0.9
maven_group=io.github.flemmli97
mod_id=debugutils
mod_author=flemmli97

# Dependencies
fabric_api_version=0.158.0+26.2

# Curse properties
curseforge_versions=26.2, Java 25, server
curseforge_page=https://www.curseforge.com/minecraft/mc-mods/debug-utils
curseforge_id=783008
curseforge_dep_fabric=fabric-api
curseforge_dep_neoforge=
modrinth_versions=26.2, server
modrinth_page=https://modrinth.com/mod/debug-utils
modrinth_id=orux8o94
modrinth_dep_fabric=fabric-api
modrinth_dep_neoforge=

# Other
project_name=DebugUtils
full_changelog=https://github.com/Flemmli97/DebugUtils/blob/26.2/Changelog.md
discord_role=1058872019984318494
