license="GNU LGPLv3"
issueTrackerURL="https://github.com/Flemmli97/DebugUtils/issues"
[[mixins]]
config = "debugutils.mixins.json"
[[mods]]
modId="debugutils"
version="${version}"
displayName="Debug Utils"
displayURL = "${homepage_neoforge}"
iconFile = "icon.png"
authors="Flemmli97"
description='''Enables various debugging tools from mojang'''
[[dependencies.debugutils]]
modId="minecraft"
type="required"
versionRange = "[${minecraft_version},)"
ordering="NONE"
side="BOTH"
