plugins {
    id 'io.github.flemmli97.multiloader.platform-neoforge'
}

neoForge {
    runs {
        var common = project(":common")
        data {
            serverData()
            programArguments.addAll "--all", "--mod", "debugutils"
            programArguments.addAll "--output", common.file("src/generated/resources").absolutePath
        }
        client {
            jvmArgument "-XX:+AllowEnhancedClassRedefinition"
        }
    }
}